#!/usr/bin/env bash
#
# gen_provenance.sh — regenerate internal/cffi/lib/PROVENANCE.md from the per-platform
# provenance.json files (the source of truth, one per vendored lib).
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)/internal/cffi/lib"
OUT="${LIB_DIR}/PROVENANCE.md"

{
  echo "# Native lib provenance"
  echo
  echo "Generated by \`scripts/gen_provenance.sh\` from the per-platform \`provenance.json\`"
  echo "files. Records which monorepo commit each vendored \`libootle_sdk_ffi_c.a\` was built"
  echo "from. See \`docs/native-lib.md\`."
  echo
  echo "| Platform | Crate | ABI | Commit | Profile | Size | sha256 |"
  echo "|---|---|---|---|---|---|---|"
} > "${OUT}"

shopt -s nullglob
for f in "${LIB_DIR}"/*/provenance.json; do
  jq -r '
    "| \(.platform) | \(.crate_version) | \(.abi) | \(.monorepo_commit[0:12]) | \(.profile) | \(((.size_bytes / 1048576.0 * 10) | round) / 10)MB | \(.sha256[0:16])… |"
  ' "${f}" >> "${OUT}"
done

echo "==> Regenerated ${OUT}"
